<%
	gTArray(0) = "myLittleAdmin For SQL Server Ans MSDE"

	' Tree
	gTArray(1) = "myLittleAdmin Lite"

	gTArray(2) = "Connection"
	gTArray(3) = "DSN-less"
	gTArray(4) = "DSN"

	gTArray(5) = "Databases"
	gTArray(6) = "Relations"
	gTArray(7) = "Tables"
	gTArray(8) = "Views"
	gTArray(9) = "Stored Procedures"
	gTArray(10) = "Users"
	gTArray(11) = "Roles"
	gTArray(12) = "Rules"
	gTArray(13) = "Default"
	gTArray(14) = "User Defined Types"

	gTArray(15) = "Management"
	gTArray(16) = "User Defined Functions"

	gTArray(19) = "Security"
	gTArray(20) = "Logins"
	gTArray(21) = "Server Roles"

	gTArray(22) = "Preferences"
	gTArray(23) = "Skin"
	gTArray(24) = "Language"
	gTArray(25) = "Display"

	gTArray(26) = "Current activity"
	gTArray(27) = "Process info"
	gTArray(28) = "Locks / Process ID"
	gTArray(29) = "Locks / Objects"

	gTArray(30) = "Tools"
	gTArray(31) = "Query Analyser"

	gTArray(32) = "Disconnect"

	' User Level
	gTArray(40) = "User Level"
	gTArray(41) = "Restricted"
	gTArray(42) = "Advanced"
	gTArray(43) = "Experimented"
	gTArray(44) = "Level Password"
	gTArray(45) = "The level password was incorrect."

	' Common
	gTArray(50) = "Reset"
	gTArray(51) = "Cancel"
	gTArray(52) = "Edit"
	gTArray(53) = "New"
	gTArray(54) = "Submit"
	gTArray(55) = "Create"
	gTArray(56) = "Name"
	gTArray(57) = "Value"
	gTArray(58) = "Text"
	gTArray(59) = "Next Step"
	gTArray(60) = "NULL"
	gTArray(61) = "BLOB"
	gTArray(62) = "Do you really want to drop %1 ?"
	gTArray(63) = "Drop"
	gTArray(64) = "Apply"
	gTArray(65) = "Rename"
	gTArray(66) = "Error"
	gTArray(67) = "Ok"
	gTArray(68) = "Generate SQL"
	gTArray(69) = "SQLDMO must be installed on your server so that this option is available."
	gTArray(70) = "Choose between"
	gTArray(71) = "New Name"
	gTArray(72) = "Information"
	gTArray(73) = "Product"
	gTArray(74) = "Version"
	gTArray(75) = "Release"

	' Connection
	gTArray(100) = "Data Source"
	gTArray(101) = "Port"
	gTArray(102) = "Initial Catalog"
	gTArray(103) = "Provider"
	gTArray(104) = "Network Library"
	gTArray(105) = "Trusted"
	gTArray(106) = "User Name"
	gTArray(107) = "Password"
	gTArray(108) = "Save this information into a cookie"
	gTArray(109) = "Connect"

	' Server Info
	gTArray(110) = "Server"
	gTArray(111) = "Server name"
	gTArray(112) = "Server version"
	gTArray(113) = "Language"

	' Database Info
	gTArray(120) = "Database"
	gTArray(121) = "Owner"
	gTArray(122) = "Date created"
	gTArray(123) = "Size"
	gTArray(124) = "Database files"
	gTArray(125) = "Filename"
	gTArray(126) = "Filegroup"
	gTArray(127) = "Size"
	gTArray(128) = "Max size"
	gTArray(129) = "Growth"
	gTArray(130) = "Usage"
	gTArray(131) = "Last database backup"
	gTArray(132) = "Last differential backup"
	gTArray(133) = "Last transaction log backup"

	' Table List
	gTArray(150) = "Table"
	gTArray(151) = "Rows"
	gTArray(152) = "Content"
	gTArray(153) = "Structure"
	gTArray(154) = "Search"
	gTArray(155) = "New Table"
	gTArray(156) = "Table Name"
	gTArray(157) = "Field Count"

	' View List
	gTArray(160) = "View"
	gTArray(161) = "View Definition Text"
	gTArray(162) = "New View"
	gTArray(163) = "With Encryption"
	gTArray(164) = "With Check Option"

	' Stored Procedure List
	gTArray(170) = "Stored Procedure"
	gTArray(171) = "Stored Procedure Definition Text"
	gTArray(172) = "Parameter"
	gTArray(173) = "Output parameter"
	gTArray(174) = "Parameters"
	gTArray(175) = "Function Definition Text"
	gTArray(176) = "Function"
	gTArray(177) = "New Stored Procedure"
	gTArray(178) = "New User Defined Function"

	' Rule List
	gTArray(180) = "Rule"
	gTArray(181) = "Rule definition text"
	gTArray(182) = "New Rule"

	' Default List
	gTArray(190) = "Default"
	gTArray(191) = "Default definition text"
	gTArray(192) = "New Default"
	gTArray(193) = "Link to UDT"
	gTArray(194) = "Link to Columns"

	' User defined type List
	gTArray(200) = "User defined type"
	gTArray(201) = "Based type"
	gTArray(202) = "Length"
	gTArray(203) = "Allows Null values"
	gTArray(204) = "New User Defined Type"
	gTArray(205) = "User Defined Type"

	' User List
	gTArray(210) = "User name"
	gTArray(211) = "Login name"
	gTArray(212) = "New User"
	gTArray(213) = "Database role membership"
	gTArray(214) = "Permit in database role"
	gTArray(215) = "User"

	' Role List
	gTArray(220) = "Role name"
	gTArray(221) = "Role type"
	gTArray(222) = "Application"
	gTArray(223) = "Standard"
	gTArray(224) = "New Role"

	' Security
	gTArray(230) = "Logins"
	gTArray(231) = "Server roles"

	' Logins
	gTArray(240) = "Login"
	gTArray(241) = "Type"
	gTArray(242) = "Default database"
	gTArray(243) = "Default language"
	gTArray(244) = "NT Group"
	gTArray(245) = "NT User"
	gTArray(246) = "New Login"
	gTArray(247) = "Default database"
	gTArray(248) = "Default language"

	' Server Roles
	gTArray(250) = "Server Role"
	gTArray(251) = "Description"

	' Processus Info
	gTArray(260) = "spid"
	gTArray(261) = "User"
	gTArray(262) = "Database"
	gTArray(263) = "Status"
	gTArray(264) = "Opened transactions"
	gTArray(265) = "Command"
	gTArray(266) = "Program"
	gTArray(267) = "Waiting time"
	gTArray(268) = "Waiting type"
	gTArray(269) = "CPU"
	gTArray(270) = "Physical I/O"
	gTArray(271) = "Memory usage"
	gTArray(272) = "Connection time"
	gTArray(273) = "Last batch time"
	gTArray(274) = "Host"
	gTArray(275) = "Network library"
	gTArray(276) = "Network address"
	gTArray(277) = "Blocked by"
	gTArray(278) = "Not waiting"
	gTArray(279) = "Waiting"

	' Lock Spid
	gTArray(290) = "spid"
	gTArray(291) = "Object"
	gTArray(292) = "Lock type"
	gTArray(293) = "Mode"
	gTArray(294) = "Status"
	gTArray(295) = "Index"
	gTArray(296) = "Resource"
	gTArray(297) = "Object Id"
	gTArray(298) = "Index Id"

	' Table structure
	gTArray(300) = "Column"
	gTArray(301) = "Type"
	gTArray(302) = "Length"
	gTArray(303) = "Prec."
	gTArray(304) = "Scale"
	gTArray(305) = "Nullable"
	gTArray(306) = "Default"
	gTArray(307) = "Id."
	gTArray(308) = "Id. start"
	gTArray(309) = "Id. seed"
	gTArray(310) = "Row GUID"
	gTArray(311) = "Key"
	gTArray(312) = "Indexes"
	gTArray(313) = "Index"
	gTArray(314) = "Columns"
	gTArray(315) = "Primary"
	gTArray(316) = "Unique"
	gTArray(317) = "Ignore dup. keys"
	gTArray(318) = "Unique key"
	gTArray(319) = "Clustered"
	gTArray(320) = "Fill factor"
	gTArray(321) = "File group"
	gTArray(322) = "Stats no recomp."
	gTArray(323) = "Rule"
	gTArray(324) = "Relationships"
	gTArray(325) = "Relationship"
	gTArray(326) = "Primary key table"
	gTArray(327) = "Foreign key table"
	gTArray(328) = "Triggers"
	gTArray(329) = "Trigger"
	gTArray(330) = "Trigger definition text"
	gTArray(331) = "Columns"
	gTArray(332) = "Table Content"
	gTArray(333) = "View Content"
	gTArray(334) = "New Trigger"
	gTArray(335) = "New Index"
	gTArray(336) = "Index Options"
	gTArray(337) = "Pad Index"
	gTArray(338) = "New Foreign Key"
	gTArray(339) = "Foreign Key Options"
	gTArray(340) = "Check existing data"
	gTArray(341) = "Enable Constraint For Replication"
	gTArray(342) = "Cascade Update (SQLServer 2000+ only)"
	gTArray(343) = "Cascade Delete (SQLServer 2000+ only)"
	gTArray(344) = "Table File Group"
	gTArray(345) = "Text/Image File Group"
	gTArray(346) =  "New Column"
	gTArray(347) = "Constraints"
	gTArray(348) = "Constraint"
	gTArray(349) = "Constraint Definition Text"
	gTArray(350) = "New Constraint"
	gTArray(351) = "Rebuild"

	' databases
	gTArray(400) = "New database"
	gTArray(401) = "Data files (optional)"
	gTArray(402) = "Location"
	gTArray(403) = "Space allocated	"
	gTArray(404) = "Max File Size"
	gTArray(405) = "File Growth"
	gTArray(406) = "File Group"
	gTArray(407) = "Transaction log files (optional)"

	' Query Analyser
	gTArray(420) = "record(s) affected."
	gTArray(421) = "The command(s) completed successfully."
	gTArray(422) = "Show Execution Plan"
	gTArray(423) = "Max Number of displayed rows"
	gTArray(424) = "All"

	' Search
	gTArray(430) = "Exact match"
	gTArray(431) = "Starts with"
	gTArray(432) = "Contains"
	gTArray(433) = "Match All"
	gTArray(434) = "Match Any"
	gTArray(435) = "Column"
	gTArray(436) = "Condition"
	gTArray(437) = "Display"
	gTArray(438) = "Ends with"

	' Insert row
	gTArray(440) = "Insert row"
	gTArray(441) = "Insert"
	gTArray(442) = "January,February,March,April,May,June,July,August,September,October,November,December"
	gTArray(443) = "S,M,T,W,T,F,S"
	
	' Content
	gTArray(450) = "Export as XML"
	gTArray(451) = "Export as CSV"
	gTArray(452) = "Query"
	gTArray(453) = "Record(s) found"
	gTArray(454) = "Actions"
	gTArray(455) = "* indicates required field"
	gTArray(456) = "Drop selected rows"
	gTArray(457) = "Do you really want to drop all selected rows ?"
	gTArray(458) = "Edit row"
	gTArray(459) = "Text viewer"

	' Options
	gTArray(480) = "Show system objects"
	gTArray(481) = "Show system databases"
	gTArray(482) = "Show system tables"
	gTArray(483) = "Show system views"
	gTArray(484) = "Show system procedures"
	gTArray(485) = "Show system functions"
	gTArray(486) = "Number of records per page"
	gTArray(487) = "Number of chars displayed in text field"
	gTArray(488) = "Number of chars displayed in binary field"
	gTArray(489) = "Row delimiter for CSV export"
	gTArray(490) = "First day of week"
	gTArray(491) = "Choose a language"
	gTArray(492) = "Choose a theme"

	' Link
	gTArray(500) = "Link"
	gTArray(501) = "Future only"
	gTArray(502) = "From table"

	' Misc.
	gTArray(510) = "Current connection string"
	gTArray(511) = "Your session has expired. You need to reconnect."
	gTArray(512) = "Use the tree on the left frame to navigate."
	gTArray(513) = "Navigation"
	gTArray(514) = "Please wait while the tree is loading..."
	gTArray(515) = "Quick Help"

%>