<%
	gTArray(0) = "myLittleAdmin Pour SQL Server And MSDE"

	' Tree
	gTArray(1) = "myLittleAdmin Lite"

	gTArray(2) = "Connexion"
	gTArray(3) = "DSN-less"
	gTArray(4) = "DSN"

	gTArray(5) = "Bases de données"
	gTArray(6) = "Relations"
	gTArray(7) = "Tables"
	gTArray(8) = "Vues"
	gTArray(9) = "Procédures stockées"
	gTArray(10) = "Utilisateurs"
	gTArray(11) = "Rôles"
	gTArray(12) = "Règles"
	gTArray(13) = "Par défaut"
	gTArray(14) = "Types de données utilisateur"

	gTArray(15) = "Gestion"
	gTArray(16) = "Fonctions utilisateur"

	gTArray(19) = "Sécurité"
	gTArray(20) = "Connexions"
	gTArray(21) = "Rôles du serveur"

	gTArray(22) = "Préférences"
	gTArray(23) = "Skin"
	gTArray(24) = "Langue"
	gTArray(25) = "Affichage"

	gTArray(26) = "Activité en cours"
	gTArray(27) = "Information sur le processus"
	gTArray(28) = "Verrous / Id de processus"
	gTArray(29) = "Verrous / Objets"

	gTArray(30) = "Outils"
	gTArray(31) = "Analyseur de requêtes"

	gTArray(32) = "Déconnexion"

	' User Level
	gTArray(40) = "Niveau d'utilisation"
	gTArray(41) = "Restreint"
	gTArray(42) = "Avancé"
	gTArray(43) = "Expérimenté"
	gTArray(44) = "Mot de passe du niveau"
	gTArray(45) = "Le mot de passe du niveau était incorrect."

	' Common
	gTArray(50) = "Initialiser"
	gTArray(51) = "Annuler"
	gTArray(52) = "Editer"
	gTArray(53) = "Nouveau"
	gTArray(54) = "Soumettre"
	gTArray(55) = "Créer"
	gTArray(56) = "Nom"
	gTArray(57) = "Valeur"
	gTArray(58) = "Texte"
	gTArray(59) = "Suivant"
	gTArray(60) = "NULL"
	gTArray(61) = "BLOB"
	gTArray(62) = "Voulez-vous vraiment supprimer %1 ?"
	gTArray(63) = "Supprimer"
	gTArray(64) = "Appliquer"
	gTArray(65) = "Renommer"
	gTArray(66) = "Erreur"
	gTArray(67) = "Ok"
	gTArray(68) = "Générer le SQL"
	gTArray(69) = "SQLDMO doit être installer sur le serveur pour que cette option soit active."
	gTArray(70) = "Choisissez entre"
	gTArray(71) = "Nouveau Nom"
	gTArray(72) = "Information"
	gTArray(73) = "Produit"
	gTArray(74) = "Version"
	gTArray(75) = "Release"

	' Connection
	gTArray(100) = "Source de données"
	gTArray(101) = "Port"
	gTArray(102) = "Catalogue par défaut"
	gTArray(103) = "Pilote"
	gTArray(104) = "Bibliothèque réseau"
	gTArray(105) = "Trusted"
	gTArray(106) = "ID de connexion"
	gTArray(107) = "Mot de passe"
	gTArray(108) = "Enregistrer ces informations dans un cookie"
	gTArray(109) = "Connecter"

	' Server Info
	gTArray(110) = "Serveur"
	gTArray(111) = "Nom du serveur"
	gTArray(112) = "Version du serveur"
	gTArray(113) = "Langue"

	' Database Info
	gTArray(120) = "Base de données"
	gTArray(121) = "Propriétaire"
	gTArray(122) = "Date de création"
	gTArray(123) = "Taille"
	gTArray(124) = "Fichiers de la base de données"
	gTArray(125) = "Nom du fichier"
	gTArray(126) = "Groupe de fichiers"
	gTArray(127) = "Taille"
	gTArray(128) = "Taille maximale"
	gTArray(129) = "Croissance"
	gTArray(130) = "Usage"
	gTArray(131) = "Dernière sauvegarde de la base de données"
	gTArray(132) = "Dernière sauvegarde différentielle"
	gTArray(133) = "Dernière sauvegarde du journal des transactions"

	' Table List
	gTArray(150) = "Table"
	gTArray(151) = "Enregistrements"
	gTArray(152) = "Contenu"
	gTArray(153) = "Structure"
	gTArray(154) = "Chercher"
	gTArray(155) = "Nouvelle Table"
	gTArray(156) = "Nom de la table"
	gTArray(157) = "Nombre de champs"

	' View List
	gTArray(160) = "Vue"
	gTArray(161) = "Texte"
	gTArray(162) = "Nouvelle Vue"
	gTArray(163) = "Crypter la vue"
	gTArray(164) = "Options de vérification"

	' Stored Procedure List
	gTArray(170) = "Procédure stockée"
	gTArray(171) = "Texte"
	gTArray(172) = "Paramètre"
	gTArray(173) = "Paramètre de sortie"
	gTArray(174) = "Paramètres"
	gTArray(175) = "Texte"
	gTArray(176) = "Fonction Utilisateur"
	gTArray(177) = "Nouvelle Procédure stockée"
	gTArray(178) = "Nouvelle Fonction utilisateur"

	' Rule List
	gTArray(180) = "Règle"
	gTArray(181) = "Texte"
	gTArray(182) = "Nouvelle Règle"

	' Default List
	gTArray(190) = "Par défaut"
	gTArray(191) = "Texte"
	gTArray(192) = "Nouveau Par défaut"
	gTArray(193) = "Lier aux UDT"
	gTArray(194) = "Lier aux colonnes"

	' User defined type List
	gTArray(200) = "Type de données utilisateur"
	gTArray(201) = "Type de base"
	gTArray(202) = "Longueur"
	gTArray(203) = "Autoriser les valeurs Null"
	gTArray(204) = "Nouveau Type de données utilisateur"
	gTArray(205) = "Type de données utilisateur"

	' User List
	gTArray(210) = "Nom d'utilisateur"
	gTArray(211) = "Nom de connexion"
	gTArray(212) = "Nouvel Utilisateur"
	gTArray(213) = "Membre du rôle de la base de données"
	gTArray(214) = "Autoriser dans le rôle de base de données"
	gTArray(215) = "Utilisateur"

	' Role List
	gTArray(220) = "Nom du rôle"
	gTArray(221) = "Type de rôle"
	gTArray(222) = "Application"
	gTArray(223) = "Standard"
	gTArray(224) = "Nouveau Rôle"

	' Security
	gTArray(230) = "Connexions"
	gTArray(231) = "Rôles du serveur"

	' Logins
	gTArray(240) = "Nom de connexion"
	gTArray(241) = "Type"
	gTArray(242) = "Base de données par défaut"
	gTArray(243) = "Langue par défaut"
	gTArray(244) = "Groupe NT"
	gTArray(245) = "Utilisateur NT"
	gTArray(246) = "Nouvelle connexion"
	gTArray(247) = "Base de données par défaut"
	gTArray(248) = "Langue par défaut"

	' Server Roles
	gTArray(250) = "Rôle du serveur"
	gTArray(251) = "Description"

	' Processus Info
	gTArray(260) = "spid"
	gTArray(261) = "Utilisateur"
	gTArray(262) = "Base de données"
	gTArray(263) = "Etat"
	gTArray(264) = "Transactions ouvertes"
	gTArray(265) = "Commande"
	gTArray(266) = "Application"
	gTArray(267) = "Temps d'attente"
	gTArray(268) = "Type d'attente"
	gTArray(269) = "UC"
	gTArray(270) = "E/S physique"
	gTArray(271) = "Utilisation de la mémoire"
	gTArray(272) = "Heure de connexion"
	gTArray(273) = "Dernier lot"
	gTArray(274) = "Hôte"
	gTArray(275) = "Bibliothèque réseau"
	gTArray(276) = "Adresse réseau"
	gTArray(277) = "Bloqué par"
	gTArray(278) = "Not waiting"
	gTArray(279) = "Waiting"

	' Lock Spid
	gTArray(290) = "spid"
	gTArray(291) = "Objet"
	gTArray(292) = "Type de verrou"
	gTArray(293) = "Mode"
	gTArray(294) = "Etat"
	gTArray(295) = "Index"
	gTArray(296) = "Ressource"
	gTArray(297) = "Id de l'object"
	gTArray(298) = "Id de l'index"

	' Table structure
	gTArray(300) = "Colonne"
	gTArray(301) = "Type de données"
	gTArray(302) = "Longueur"
	gTArray(303) = "Préc."
	gTArray(304) = "Echelle"
	gTArray(305) = "Null autorisé"
	gTArray(306) = "Valeur par défaut"
	gTArray(307) = "Compteur"
	gTArray(308) = "Début du compteur"
	gTArray(309) = "Incrément du compteur"
	gTArray(310) = "Row GUID"
	gTArray(311) = "Clé primaire"
	gTArray(312) = "Index"
	gTArray(313) = "Index"
	gTArray(314) = "Colonnes"
	gTArray(315) = "Primaire"
	gTArray(316) = "Unique"
	gTArray(317) = "Ignorer les valeurs dupliquées"
	gTArray(318) = "Valeurs uniques"
	gTArray(319) = "Index ordonné en clusters"
	gTArray(320) = "Remplissage"
	gTArray(321) = "Groupe de fichiers"
	gTArray(322) = "Ne pas recalculer les statistiques"
	gTArray(323) = "Règle"
	gTArray(324) = "Relations"
	gTArray(325) = "Relation"
	gTArray(326) = "Table de clé primaire"
	gTArray(327) = "Table de clé externe"
	gTArray(328) = "Déclencheurs"
	gTArray(329) = "Déclencheur"
	gTArray(330) = "Texte"
	gTArray(331) = "Colonnes"
	gTArray(332) = "Données de la table"
	gTArray(333) = "Données de la vue"
	gTArray(334) = "Nouveau Déclencheur"
	gTArray(335) = "Nouvel Index"
	gTArray(336) = "Options d'index"
	gTArray(337) = "Index Pad"
	gTArray(338) = "Nouvelle Relation"
	gTArray(339) = "Options de relation"
	gTArray(340) = "Vérifier les données existantes"
	gTArray(341) = "Activer la relation pour la réplication"
	gTArray(342) = "Update en cascade (SQLServer 2000+ seulement)"
	gTArray(343) = "Delete en cascate(SQLServer 2000+ seulement)"
	gTArray(344) = "Groupe de fichiers de table"
	gTArray(345) = "Groupe de fichiers texte"
	gTArray(346) =  "Nouvelle Colonne"
	gTArray(347) = "Contraintes CHECK"
	gTArray(348) = "Contrainte"
	gTArray(349) = "Texte"
	gTArray(350) = "Nouvelle Contrainte"
	gTArray(351) = "Reconstruire"

	' databases
	gTArray(400) = "Nouvelle Base de données"
	gTArray(401) = "Fichiers de la base de données (optionnel)"
	gTArray(402) = "Emplacement"
	gTArray(403) = "Taille initiale	"
	gTArray(404) = "Taille maximale du fichier"
	gTArray(405) = "Croissance du fichier"
	gTArray(406) = "Groupe de fichiers"
	gTArray(407) = "Fichiers du journal de transactions (optionnel)"

	' Query Analyser
	gTArray(420) = "enregistrement(s) affectés."
	gTArray(421) = "Le(s) commande(s) se sont terminées avec succès."
	gTArray(422) = "Afficher le plan d'exécution"
	gTArray(423) = "Nombre d'enregistrements affichés"
	gTArray(424) = "Tous"

	' Search
	gTArray(430) = "Est exactement"
	gTArray(431) = "Commence par"
	gTArray(432) = "Contient"
	gTArray(433) = "Tous les critères"
	gTArray(434) = "Au moins un critère"
	gTArray(435) = "Colonne"
	gTArray(436) = "Condition"
	gTArray(437) = "Afficher"
	gTArray(438) = "Se termine par"

	' Insert row
	gTArray(440) = "Insérer un enregistrement"
	gTArray(441) = "Insérer"
	gTArray(442) = "Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre"
	gTArray(443) = "D,L,M,M,J,V,S"
	
	' Content
	gTArray(450) = "Exporter en XML"
	gTArray(451) = "Exporter en CSV"
	gTArray(452) = "Requête"
	gTArray(453) = "Enregistrement(s) trouvé(s)"
	gTArray(454) = "Actions"
	gTArray(455) = "* indique un champ obligatoire"
	gTArray(456) = "Supprimer les lignes sélectionnées"
	gTArray(457) = "Voulez-vous vraiment supprimer les lignes sélectionnées ?"
	gTArray(458) = "Editer la ligne"
	gTArray(459) = "Visualisateur de texte"

	' Options
	gTArray(480) = "Afficher les objets système"
	gTArray(481) = "Afficher les bases de données système"
	gTArray(482) = "Afficher les tables système"
	gTArray(483) = "Afficher les vues système"
	gTArray(484) = "Afficher les procédures stockées système"
	gTArray(485) = "Afficher les fonctions systèmes"
	gTArray(486) = "Nombre de lignes par page"
	gTArray(487) = "Nombre de caractères affichés pour les colonnes alphanumériques"
	gTArray(488) = "Nombre de caractères affichés pour les colonnes binaires"
	gTArray(489) = "Délimiteur de colonne pour les exports CSV"
	gTArray(490) = "Premier jour de la semaine"
	gTArray(491) = "Choisir une langue"
	gTArray(492) = "Choisir un thème"

	' Link
	gTArray(500) = "Lier"
	gTArray(501) = "Future only"
	gTArray(502) = "Table"

	' Misc.
	gTArray(510) = "Chaîne de connexion actuelle"
	gTArray(511) = "Votre session a expiré. Vous devez vous reconnecter."
	gTArray(512) = "Utiliser l'arborescence dans le cadre de gauche pour naviguer."
	gTArray(513) = "Navigation"
	gTArray(514) = "Merci de patienter pendant que l'arborescence se charge..."
	gTArray(515) = "Aide"

%>